// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvtbizeIVpcgbucenzezeZuu_boGWR3A',
    appId: '1:191840507553:web:a684089b25fdf19bd002e0',
    messagingSenderId: '191840507553',
    projectId: 'weather-57d78',
    authDomain: 'weather-57d78.firebaseapp.com',
    storageBucket: 'weather-57d78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADFd1vUekJ7SyywomFw2ApzuPKx6jl8q0',
    appId: '1:191840507553:android:a249036505824b44d002e0',
    messagingSenderId: '191840507553',
    projectId: 'weather-57d78',
    storageBucket: 'weather-57d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1sD2ypJ-Z4h0VWf7Nh8so4q-eCbcIRA4',
    appId: '1:191840507553:ios:6e4de15f6acf9ac8d002e0',
    messagingSenderId: '191840507553',
    projectId: 'weather-57d78',
    storageBucket: 'weather-57d78.appspot.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1sD2ypJ-Z4h0VWf7Nh8so4q-eCbcIRA4',
    appId: '1:191840507553:ios:6e4de15f6acf9ac8d002e0',
    messagingSenderId: '191840507553',
    projectId: 'weather-57d78',
    storageBucket: 'weather-57d78.appspot.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARvtbizeIVpcgbucenzezeZuu_boGWR3A',
    appId: '1:191840507553:web:d4c48fbdb16ffd5ad002e0',
    messagingSenderId: '191840507553',
    projectId: 'weather-57d78',
    authDomain: 'weather-57d78.firebaseapp.com',
    storageBucket: 'weather-57d78.appspot.com',
  );
}
